### ISSUE TITLE
download tab and published tab fails to recognize previous content(download/upload)

### ISSUE THREAD

**Issue by arainflake** [lbryio/lbry#750] opened 2017-07-01 21:37 UTC
## The Issue
The download and published pages wont actually display what i have downloaded or published unless i have done it withing the current session, and so, after closing lbry and then restarting the files are no longer displayed, but are still in their respective folders on my computer, as in they have not been deleted, its just that they are no longer recognized as files i have downloaded.
To get the file displayed in the lbry download tab, i can either; download a new file, which will then be displayed properly in the download tab, or simply go to the page of a file i have already downloaded, and then go back to the downloaded tab, and it will be displayed properly

### Steps to reproduce
1.open lbry gui
2.go to download tab
3.previously downloaded content not displayed

### Expected behaviour
Tell us what should happen
-the previously downloaded content should definitely be there, as it is if i download something during the current session

### Actual behaviour
Tell us what happens instead
-upon opening a fresh lbry app, there is nothing in either the download tab or the published tab(i have published one thing, it is also not displayed)

## System Configuration
-xfce version
-Linux (Linux-4.4.0-79-generic-x86_64-with-LinuxMint-18.1-serena)

 

- LBRY Daemon version:0.13.1
- LBRY App version:0.13.0
- LBRY Installation ID:3Ra4EZXfac42br3RS72AXXWCm7tff4KSbiJnGwUNhaqkNYeXsdxPhUsjF5Lq6Lrhmv
- Operating system:-Linux (Linux-4.4.0-79-generic-x86_64-with-LinuxMint-18.1-serena)

## Anything Else

-this has actually been a problem since version 0.8 or so, i thought it would be fixed in later versions, but since nothing has been done yet (either because the problem hasn’t been found or no one else has noticed it), i've decided now would be as good a time as any to let you guys know.

-the first picture is when i start up lbry and go straight to the download tab.
the second picture is after i go to the video page, but not download and not watch the video, just simply going to it, and then heading back to the download page, then the content is displayed properly

-the second and third pictures show the multiple files in my download folder used for lbry content, and the corresponding path in the lbry settings page, which are both the same.

![download pic](https://user-images.githubusercontent.com/27785632/27765557-9c1fe63e-5e82-11e7-97c4-8b377c0d7173.jpg)
![download after video browse](https://user-images.githubusercontent.com/27785632/27765559-a35274a8-5e82-11e7-8056-364bf49a8987.png)
![download folder path setting](https://user-images.githubusercontent.com/27785632/27765589-7f85c4fc-5e83-11e7-8c70-b2f52575d861.png)
![my lbry downloads folder](https://user-images.githubusercontent.com/27785632/27765588-7f8330e8-5e83-11e7-8d21-ba6c525d017c.jpg)

**Comment by tzarebczan** [comment] 2017-07-03 18:18
This is a duplicate of https://github.com/lbryio/lbry/issues/661 

It should be fixed in the next version. I'll double check.

**Comment by tzarebczan** [comment] 2017-07-03 20:22
@arainflake can you upload your lbrynet.log file (you can strip out your IP if it shows) 

Thanks!

**Comment by arainflake** [comment] 2017-07-04 00:02
[lbrynet..txt](https://github.com/lbryio/lbry/files/1120729/lbrynet.txt)

**Comment by arainflake** [comment] 2017-07-04 00:05
i did read #661 to see if it was the same, and while checking the log file, saw an error that read:
Failed to process file_list: string indices must be integers

so it looks like it might be the same problem

**Comment by tzarebczan** [comment] 2017-07-04 18:32
@arainflake we'll have a new version you can try out soon, but it's supposed to fix the windows issue only. We will have you try it again, but this looks like a new valid issue you have here. Will keep you updated.

**Comment by tzarebczan** [comment] 2017-07-05 00:19
I'm getting this same error now after testing https://github.com/lbryio/lbry/pull/746 successfully - I guess it was able to bypass the Unicode issue, but now errors on the "list indices must be integers, not str" when my app starts up.  I am now able to see items in my Download/Publishes, but the loading icon right above the first item still shows like it's trying to do more. 

After a reboot and trying to stream some more items (I know I went to lbry://@CasuallyExplained/casually-successful and lbry://hitmans-bodyguard-trailer but not sure if its to blame), I can't get My Downloads/Publishes to show again - gets stuck at loading.  Neither of those 2 URI will download for me. I'll try to reproduce this on my laptop. 

@kaykurokawa  - let me know if you need any additional info from me, but I'm guessing its something related to an old file or publish. 

`{
  "error": {
    "code": -32500,
    "data": {
      "traceback": [
        "Traceback (most recent call last):",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 498, in errback",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 565, in _startRunCallbacks",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 651, in _runCallbacks",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1355, in gotResult",
        "    ",
        "--- <exception caught here> ---",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1297, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\twisted\\python\\failure.py\", line 389, in throwExceptionIntoGenerator",
        "    ",
        "  File \"site-packages\\lbrynet\\daemon\\Daemon.py\", line 1294, in jsonrpc_file_list",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1297, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\twisted\\python\\failure.py\", line 389, in throwExceptionIntoGenerator",
        "    ",
        "  File \"site-packages\\lbrynet\\daemon\\Daemon.py\", line 928, in _get_lbry_files",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1297, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\twisted\\python\\failure.py\", line 389, in throwExceptionIntoGenerator",
        "    ",
        "  File \"site-packages\\lbrynet\\daemon\\Daemon.py\", line 850, in _get_lbry_file_dict",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1297, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\twisted\\python\\failure.py\", line 389, in throwExceptionIntoGenerator",
        "    ",
        "  File \"site-packages\\lbrynet\\core\\Wallet.py\", line 658, in get_claim",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1297, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\twisted\\python\\failure.py\", line 389, in throwExceptionIntoGenerator",
        "    ",
        "  File \"site-packages\\lbrynet\\core\\Wallet.py\", line 653, in get_cached_claim",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1299, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\lbrynet\\core\\Wallet.py\", line 134, in get_cached_claim",
        "    ",
        "  File \"site-packages\\lbrynet\\core\\Wallet.py\", line 78, in __init__",
        "    ",
        "exceptions.TypeError: list indices must be integers, not str",
        ""
      ]
    },
    "message": "list indices must be integers, not str"
  },
  "id": 194,
  "jsonrpc": "2.0"
}
`

**Comment by tzarebczan** [comment] 2017-07-08 00:04
After clearing my blockchainname.db file, my Downloads are now showing correctly.  My Publishes page is blank for som reason though...very strange - maybe someway connected to blockchainname.db .  

Since https://github.com/lbryio/lbry-app/issues/315 is happening, don't think there is a reason to investigate any further.

**Comment by kaykurokawa** [comment] 2017-07-11 17:01
We still need to fix this because Downloads still rely on file_list. 

I've found that the root issue was that there were malformed supports data entering the claim cache. See final fix : https://github.com/lbryio/lbry/pull/759.

**Closed** 2017-07-14 20:41 UTC
Labels: bug
