### ISSUE TITLE
BaseException: expected string or buffer

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#609] opened 2017-04-14 16:29 UTC
While running Franklin on the 40 EA homepage names, got this error on `lbry://@CryptoverseLBRY:1/cryptoverse-246`

```
Apr 14 15:55:14 test lbrynet-daemon[20967]: 2017-04-14 15:55:14,187 ERROR    lbrynet.lbrynet_daemon.auth.server:352: Failed to process stream_cost_estimate: expected string or buffer
Apr 14 15:55:14 test lbrynet-daemon[20967]: Traceback (most recent call last):
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 1723, in jsonrpc_stream_cost_estimate
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 891, in get_est_cost_from_uri
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbrynet/core/Wallet.py", line 584, in resolve_uri
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/python/threadpool.py", line 246, in inContext
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/python/threadpool.py", line 262, in <lambda>
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/python/context.py", line 118, in callWithContext
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/twisted/python/context.py", line 81, in callWithContext
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbryum/commands.py", line 152, in func_wrapper
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbryum/commands.py", line 932, in getvalueforuri
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbryum/commands.py", line 152, in func_wrapper
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbryum/commands.py", line 900, in getclaimbynameinchannel
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbryum/commands.py", line 152, in func_wrapper
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbryum/commands.py", line 1055, in getclaimsinchannel
Apr 14 15:55:14 test lbrynet-daemon[20967]:   File "site-packages/lbryum/network.py", line 805, in synchronous_get
Apr 14 15:55:14 test lbrynet-daemon[20967]: BaseException: expected string or buffer
```

**Comment by kaykurokawa** [comment] 2017-04-17 17:09
I can't reproduce this

**Comment by kaykurokawa** [comment] 2017-04-17 21:29
This is a problem with @epicentertv:1/epicenter-172 it looks like

**Comment by kaykurokawa** [comment] 2017-04-18 01:00
fixed in lbryum server https://github.com/lbryio/lbryum-server/pull/21

**Comment by jackrobison** [comment] 2017-04-18 18:26
Merged https://github.com/lbryio/lbryum-server/pull/21

**Closed by jackrobison** 2017-04-18 18:26 UTC
