### ISSUE TITLE
Speed up claim resolution

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#956] opened 2017-10-16 17:53 UTC
## The Issue
I know we've had some discussions on how to speed up the claim resolution process and now seems like a good time to tackle this since implementing multi-resolve.  With multi-resolve, the claim resolutions on the home page are batched, so when someone completely refreshes the cache or runs LBRY for the first time, it may look like nothing is happening for an extended period of time before all the results come back. We will also want to employ batch resolution in more places like search results, Downloads page, Publishes, etc.  

The goal of this ticket is to increase the performance/efficiency of the resolve process.  

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment] 2017-11-21 05:03
@lyoshenka we should bump this up in priority - it affects first run experience. It stays on the validating screen for all tiles for at least 1 minute (on a fast machine). On Paul's desktop in Manchester, it took like 3 minutes.

**Comment by lyoshenka** [comment] 2018-02-21 15:36
duplicate of lbryio/lbryum-server#49

**Closed by lyoshenka** 2018-02-21 15:36 UTC
Labels: Tom's Wishlist, area: wallet, level: 3, type: improvement
