### ISSUE TITLE
on startup, try_upnp takes a long time if on a non upnp enabled network 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbry#284] opened 2016-11-22 16:36 UTC
try_upnp function in Session will take a long time (over a minute) during startup before failing and continuing to startup

**Comment by mirgee** [comment] 2017-09-22 08:08
Unable to reproduce, can anyone verify this is still an issue?

**Comment by tzarebczan** [comment] 2017-09-22 16:06
I haven't seen this one creep up lately and it would most likely be related to some local network issues with ports/UPNP.  Not sure how to reproduce.

**Comment by lyoshenka** [comment] 2017-09-26 13:15
Closing this. Reopen if you see it again.

**Closed by lyoshenka** 2017-09-26 13:15 UTC
Labels: bug, P3
