### ISSUE TITLE
Exception when stopping daemon with Ctrl-C

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#626] opened 2017-04-26 17:43 UTC
### Steps to Reproduce:

- start daemon
- wait for the message `Using lbryum wallet`
- press `Ctrl-C`

### Sample Error Message

```
2018-01-16 11:43:01,582 INFO     lbrynet.daemon.DaemonControl:81: Starting lbrynet-daemon from command line
2018-01-16 11:43:02,099 INFO     lbrynet.daemon.DaemonServer:64: Using non-authenticated API
2018-01-16 11:43:02,100 INFO     lbrynet.daemon.Daemon:243: Starting lbrynet-daemon
2018-01-16 11:43:02,198 INFO     lbrynet.daemon.ExchangeRateManager:210: Starting exchange rate manager
2018-01-16 11:43:02,625 INFO     lbrynet.daemon.Daemon:271: Platform: {"lbrynet_version": "0.19.0rc26", "platform": "Linux-4.4.0-87-generic-x86_64-with-Ubuntu-16.04-xenial", "os_system": "Linux", "python_version": "2.7.12", "os_release": "4.4.0-87-generic", "lbryum_version": "3.2.0rc10", "ip": "76.169.179.127", "lbryschema_version": "0.0.15rc2", "processor": "x86_64", "build": "dev"}
2018-01-16 11:43:02,634 INFO     lbrynet.daemon.Daemon:481: Loading databases
2018-01-16 11:43:02,679 INFO     lbrynet.daemon.Daemon:511: Upgrading your databases
2018-01-16 11:43:02,681 INFO     lbrynet.db_migrator.migrate4to5:9: Doing the migration
2018-01-16 11:43:03,048 INFO     lbrynet.db_migrator.migrate4to5:11: Migration succeeded
2018-01-16 11:43:03,048 INFO     lbrynet.daemon.Daemon:507: Finished upgrading the databases.
2018-01-16 11:43:03,048 INFO     lbrynet.daemon.Daemon:547: Using lbryum wallet
2018-01-16 11:43:03,207 WARNING  lbrynet.core.Session:243: UPnP failed. Reason: Invalid Action
2018-01-16 11:43:03,208 INFO     lbrynet.core.Session:254: Starting DHT
2018-01-16 11:43:03,264 INFO     lbrynet.dht.protocol:178: DHT listening on UDP 4444
^C
2018-01-16 11:43:03,981 INFO     lbrynet.daemon.Daemon:408: Closing lbrynet session
2018-01-16 11:43:03,982 INFO     lbrynet.daemon.Daemon:409: Status at time of shutdown: loading_wallet
2018-01-16 11:43:03,982 INFO     lbrynet.core.Session:172: Stopping session.
2018-01-16 11:43:03,982 INFO     lbrynet.core.client.DHTPeerFinder:32: Stopping DHT peer finder.
2018-01-16 11:43:03,982 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping DHT hash announcer.
2018-01-16 11:43:03,982 INFO     lbrynet.core.Wallet:478: Stopping wallet.
2018-01-16 11:43:03,983 ERROR    lbrynet.core.Wallet:544: Something went wrong during manage. Error message: 'NoneType' object has no attribute 'get_balance'
2018-01-16 11:43:03,994 ERROR    lbrynet.core.Wallet:475: An error occurred stopping the wallet: Traceback (most recent call last):
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 308, in addCallbacks
    self._runCallbacks()
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/grin/lbry/lbrynet/core/Wallet.py", line 531, in <lambda>
    d.addCallbacks(lambda _: self.update_balance(), log_error)
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/grin/lbry/lbrynet/core/Wallet.py", line 561, in update_balance
    balance = yield self._update_balance()
  File "/home/grin/lbry/lbrynet/core/Wallet.py", line 1374, in _update_balance
    d = self._run_cmd_as_defer_succeed('getbalance', accounts, exclude_claimtrietx)
  File "/home/grin/lbry/lbrynet/core/Wallet.py", line 1359, in _run_cmd_as_defer_succeed
    return defer.succeed(func(*args, **kwargs))
  File "/home/grin/.virtualenvs/lbry/local/lib/python2.7/site-packages/lbryum/commands.py", line 378, in getbalance
    c, u, x = self.wallet.get_balance(exclude_claimtrietx=exclude_claimtrietx)
exceptions.AttributeError: 'NoneType' object has no attribute 'get_balance'

2018-01-16 11:43:03,994 INFO     lbrynet.core.Session:324: Unsetting upnp for session
2018-01-16 11:43:03,995 INFO     lbrynet.dht.protocol:445: Stopping DHT
2018-01-16 11:43:03,995 INFO     lbrynet.dht.protocol:461: DHT stopped

```

**Comment by lyoshenka** [comment] 2017-04-26 17:43
I'm guessing this happens if you kill the daemon at just the wrong moment.

**Comment by lyoshenka** [comment] 2017-04-26 17:51
More info: happens if you press ctrl+C right after this message: `lbrynet.lbrynet_daemon.Daemon:560: Using lbryum wallet`

**Comment by lyoshenka** [comment] 2017-09-26 13:12
Still happens. Here's the new error message: 

```
2017-09-26 13:11:47,016 INFO     lbrynet.daemon.Daemon:471: Loading databases
2017-09-26 13:11:47,017 INFO     lbrynet.daemon.Daemon:537: Using lbryum wallet
^C2017-09-26 13:11:47,737 INFO     lbrynet.daemon.Daemon:400: Closing lbrynet session
2017-09-26 13:11:47,737 INFO     lbrynet.daemon.Daemon:401: Status at time of shutdown: loading_wallet
2017-09-26 13:11:47,737 INFO     lbrynet.core.Session:172: Stopping session.
2017-09-26 13:11:47,738 INFO     lbrynet.core.Wallet:476: Stopping wallet.
2017-09-26 13:11:47,738 ERROR    lbrynet.core.Wallet:542: Something went wrong during manage. Error message: 'NoneType' object has no attribute 'get_balance'
2017-09-26 13:11:47,740 ERROR    lbrynet.core.Wallet:473: An error occurred stopping the wallet: Traceback (most recent call last):
  File "site-packages/twisted/internet/defer.py", line 308, in addCallbacks
    
  File "site-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    
  File "site-packages/lbrynet/core/Wallet.py", line 529, in <lambda>
    
  File "site-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    
--- <exception caught here> ---
  File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    
  File "site-packages/lbrynet/core/Wallet.py", line 559, in update_balance
    
  File "site-packages/lbrynet/core/Wallet.py", line 1303, in _update_balance
    
  File "site-packages/lbrynet/core/Wallet.py", line 1288, in _run_cmd_as_defer_succeed
    
  File "site-packages/lbryum/commands.py", line 91, in func_wrapper
    
  File "site-packages/lbryum/commands.py", line 309, in getbalance
    
exceptions.AttributeError: 'NoneType' object has no attribute 'get_balance'

2017-09-26 13:11:47,741 INFO     lbrynet.core.Session:323: Unsetting upnp for session
```

**Comment by GWBasic** [comment] 2018-02-04 01:03
I might have a fix in my branch at: https://github.com/lbryio/lbry/compare/master...GWBasic:626_ExceptionWhenShuttingDownAtStartup?expand=1

Is there any way to run unit tests or some kind of automated tests before I make a pull request?

**Comment by tzarebczan** [comment] 2018-02-09 01:27
@GWBasic looks like someone submitted a PR for this already: https://github.com/lbryio/lbry/pull/1095

Best way to test the fix would be to follow the reproduction steps noted in the original issue. I'm not sure any unit tests would catch this.

**Comment by kauffj** [comment] 2018-02-09 21:03
@lyoshenka can you please give @GWBasic some guidance for this? Andrew is working on this issue as protocol engineer candidate.

**Comment by lyoshenka** [comment] 2018-02-23 22:11
sorry for the slow response. run `PYTHONPATH=. trial lbrynet.tests` to run the tests. you may need to install a few packages to get it to run. check the `script` section of `.travis.yml`

**Comment by alyssaoc** [comment] 2018-07-19 14:58
@tzarebczan Is this still an issue?

**Comment by tzarebczan** [comment] 2018-08-14 21:45
I think this may have been fixed by the components refactor. I tried a few times by stopping with ctrl-c at various points, and it aborted cleanly. 

@lyoshenka (or anyone else) if you run across this on 0.21+, please reopen.
```

018-08-14 17:40:34,398 INFO     lbrynet.daemon.DaemonControl:84: Starting lbrynet-daemon from command line
2018-08-14 17:40:35,329 INFO     lbrynet.daemon.auth.factory:36: Using non-authenticated API
2018-08-14 17:40:35,331 INFO     lbrynet.daemon.auth.server:223: lbrynet API listening on TCP localhost:5279
2018-08-14 17:40:35,332 INFO     lbrynet.daemon.Daemon:235: Starting lbrynet-daemon
2018-08-14 17:40:35,447 INFO     lbrynet.daemon.Daemon:236: Platform: {"lbrynet_version": "0.21.1", "platform": "Windows-10-10.0.17134", "os_system": "Windows", "python_version": "2.7.15", "os_release": "10", "lbryum_version": "3.2.4", "ip": "74.105.116.110", "lbryschema_version": "0.0.16", "processor": "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel", "build": "release"}
2018-08-14 17:40:35,634 INFO     lbrynet.daemon.Components:127: Loading databases
2018-08-14 17:40:35,634 INFO     lbrynet.database.storage:174: connecting to database: C:\Users\SoloDolo\AppData\Roaming\lbrynet\lbrynet.sqlite
2018-08-14 17:40:35,637 INFO     lbrynet.daemon.ExchangeRateManager:217: Starting exchange rate manager
2018-08-14 17:40:35,678 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2018-08-14 17:40:35,762 INFO     lbrynet.daemon.Components:259: victor.lbry.tech:50001 height: 419988, local height: 419988
2018-08-14 17:40:36,180 INFO     lbrynet.daemon.auth.server:231: shutting down before finished starting
2018-08-14 17:40:36,293 INFO     lbrynet.daemon.ExchangeRateManager:222: Stopping exchange rate manager
2018-08-14 17:40:36,295 INFO     lbrynet.core.RateLimiter:83: Stopping rate limiter.
2018-08-14 17:41:44,838 INFO     lbrynet.daemon.DaemonControl:84: Starting lbrynet-daemon from command line
2018-08-14 17:41:45,779 INFO     lbrynet.daemon.auth.factory:36: Using non-authenticated API
2018-08-14 17:41:45,782 INFO     lbrynet.daemon.auth.server:223: lbrynet API listening on TCP localhost:5279
2018-08-14 17:41:45,782 INFO     lbrynet.daemon.Daemon:235: Starting lbrynet-daemon
2018-08-14 17:41:45,905 INFO     lbrynet.daemon.Daemon:236: Platform: {"lbrynet_version": "0.21.1", "platform": "Windows-10-10.0.17134", "os_system": "Windows", "python_version": "2.7.15", "os_release": "10", "lbryum_version": "3.2.4", "ip": "74.105.116.110", "lbryschema_version": "0.0.16", "processor": "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel", "build": "release"}
2018-08-14 17:41:46,096 INFO     lbrynet.daemon.Components:127: Loading databases
2018-08-14 17:41:46,121 INFO     lbrynet.database.storage:174: connecting to database: C:\Users\SoloDolo\AppData\Roaming\lbrynet\lbrynet.sqlite
2018-08-14 17:41:46,121 INFO     lbrynet.daemon.ExchangeRateManager:217: Starting exchange rate manager
2018-08-14 17:41:46,161 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2018-08-14 17:41:46,266 INFO     lbrynet.daemon.Components:259: victor.lbry.tech:50001 height: 419989, local height: 419988
2018-08-14 17:41:46,661 INFO     lbrynet.daemon.auth.server:231: shutting down before finished starting
2018-08-14 17:41:46,786 INFO     lbrynet.daemon.ExchangeRateManager:222: Stopping exchange rate manager
2018-08-14 17:41:46,786 INFO     lbrynet.core.RateLimiter:83: Stopping rate limiter.
2018-08-14 17:41:58,898 INFO     lbrynet.daemon.DaemonControl:84: Starting lbrynet-daemon from command line
2018-08-14 17:41:59,888 INFO     lbrynet.daemon.auth.factory:36: Using non-authenticated API
2018-08-14 17:41:59,888 INFO     lbrynet.daemon.auth.server:223: lbrynet API listening on TCP localhost:5279
2018-08-14 17:41:59,890 INFO     lbrynet.daemon.Daemon:235: Starting lbrynet-daemon
2018-08-14 17:42:00,013 INFO     lbrynet.daemon.Daemon:236: Platform: {"lbrynet_version": "0.21.1", "platform": "Windows-10-10.0.17134", "os_system": "Windows", "python_version": "2.7.15", "os_release": "10", "lbryum_version": "3.2.4", "ip": "74.105.116.110", "lbryschema_version": "0.0.16", "processor": "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel", "build": "release"}
2018-08-14 17:42:00,203 INFO     lbrynet.daemon.Components:127: Loading databases
2018-08-14 17:42:00,203 INFO     lbrynet.database.storage:174: connecting to database: C:\Users\SoloDolo\AppData\Roaming\lbrynet\lbrynet.sqlite
2018-08-14 17:42:00,204 INFO     lbrynet.daemon.ExchangeRateManager:217: Starting exchange rate manager
2018-08-14 17:42:00,243 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2018-08-14 17:42:00,329 INFO     lbrynet.daemon.Components:259: victor.lbry.tech:50001 height: 419989, local height: 419988
2018-08-14 17:42:02,651 WARNING  lbrynet.daemon.Components:692: failed to set up redirect with txupnp, miniupnpc fallback was successful
2018-08-14 17:42:02,993 INFO     lbrynet.dht.protocol:202: DHT listening on UDP 4446 (ext port 4446)
2018-08-14 17:42:02,994 INFO     lbrynet.daemon.Components:417: Started the dht
2018-08-14 17:42:02,996 INFO     lbrynet.core.Wallet:92: Starting wallet.
2018-08-14 17:42:03,026 INFO     lbrynet.core.Wallet:880: Loading the wallet
2018-08-14 17:42:05,253 WARNING  lbrynet.core.Wallet:963: Your wallet is excessively large (2687 addresses), please follow instructions here: https://github.com/lbryio/lbry/issues/437 to reduce your wallet size
2018-08-14 17:42:05,266 INFO     lbrynet.daemon.auth.server:231: shutting down before finished starting
2018-08-14 17:42:05,269 INFO     lbrynet.dht.protocol:493: Stopping DHT
2018-08-14 17:42:05,269 INFO     lbrynet.dht.protocol:496: DHT stopped
2018-08-14 17:42:05,387 INFO     lbrynet.daemon.ExchangeRateManager:222: Stopping exchange rate manager
2018-08-14 17:42:05,387 INFO     lbrynet.core.RateLimiter:83: Stopping rate limiter.
2018-08-14 17:42:26,270 INFO     lbrynet.daemon.DaemonControl:84: Starting lbrynet-daemon from command line
2018-08-14 17:42:27,177 INFO     lbrynet.daemon.auth.factory:36: Using non-authenticated API
2018-08-14 17:42:27,180 INFO     lbrynet.daemon.auth.server:223: lbrynet API listening on TCP localhost:5279
2018-08-14 17:42:27,180 INFO     lbrynet.daemon.Daemon:235: Starting lbrynet-daemon
2018-08-14 17:42:27,316 INFO     lbrynet.daemon.Daemon:236: Platform: {"lbrynet_version": "0.21.1", "platform": "Windows-10-10.0.17134", "os_system": "Windows", "python_version": "2.7.15", "os_release": "10", "lbryum_version": "3.2.4", "ip": "74.105.116.110", "lbryschema_version": "0.0.16", "processor": "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel", "build": "release"}
2018-08-14 17:42:27,506 INFO     lbrynet.daemon.Components:127: Loading databases
2018-08-14 17:42:27,507 INFO     lbrynet.database.storage:174: connecting to database: C:\Users\SoloDolo\AppData\Roaming\lbrynet\lbrynet.sqlite
2018-08-14 17:42:27,509 INFO     lbrynet.daemon.ExchangeRateManager:217: Starting exchange rate manager
2018-08-14 17:42:27,551 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2018-08-14 17:42:27,630 INFO     lbrynet.daemon.Components:259: victor.lbry.tech:50001 height: 419990, local height: 419989
2018-08-14 17:42:29,648 WARNING  lbrynet.daemon.Components:692: failed to set up redirect with txupnp, miniupnpc fallback was successful
2018-08-14 17:42:29,727 INFO     lbrynet.dht.protocol:202: DHT listening on UDP 4446 (ext port 4446)
2018-08-14 17:42:29,729 INFO     lbrynet.daemon.Components:417: Started the dht
2018-08-14 17:42:29,730 INFO     lbrynet.core.Wallet:92: Starting wallet.
2018-08-14 17:42:29,755 INFO     lbrynet.core.Wallet:880: Loading the wallet
2018-08-14 17:42:31,986 WARNING  lbrynet.core.Wallet:963: Your wallet is excessively large (2687 addresses), please follow instructions here: https://github.com/lbryio/lbry/issues/437 to reduce your wallet size
2018-08-14 17:42:32,007 INFO     lbrynet.dht.node:250: Attempting to join the DHT network, 0 contacts known so far
2018-08-14 17:42:32,551 INFO     lbrynet.daemon.auth.server:231: shutting down before finished starting
2018-08-14 17:42:32,552 INFO     lbrynet.dht.protocol:493: Stopping DHT
2018-08-14 17:42:32,553 INFO     lbrynet.dht.protocol:496: DHT stopped
2018-08-14 17:42:32,667 INFO     lbrynet.daemon.ExchangeRateManager:222: Stopping exchange rate manager
2018-08-14 17:42:32,668 INFO     lbrynet.core.RateLimiter:83: Stopping rate limiter.
2018-08-14 17:42:55,467 INFO     lbrynet.daemon.DaemonControl:84: Starting lbrynet-daemon from command line
2018-08-14 17:42:56,476 INFO     lbrynet.daemon.auth.factory:36: Using non-authenticated API
2018-08-14 17:42:56,477 INFO     lbrynet.daemon.auth.server:223: lbrynet API listening on TCP localhost:5279
2018-08-14 17:42:56,479 INFO     lbrynet.daemon.Daemon:235: Starting lbrynet-daemon
2018-08-14 17:42:56,591 INFO     lbrynet.daemon.Daemon:236: Platform: {"lbrynet_version": "0.21.1", "platform": "Windows-10-10.0.17134", "os_system": "Windows", "python_version": "2.7.15", "os_release": "10", "lbryum_version": "3.2.4", "ip": "74.105.116.110", "lbryschema_version": "0.0.16", "processor": "Intel64 Family 6 Model 158 Stepping 9, GenuineIntel", "build": "release"}
2018-08-14 17:42:56,799 INFO     lbrynet.daemon.Components:127: Loading databases
2018-08-14 17:42:56,801 INFO     lbrynet.database.storage:174: connecting to database: C:\Users\SoloDolo\AppData\Roaming\lbrynet\lbrynet.sqlite
2018-08-14 17:42:56,802 INFO     lbrynet.daemon.ExchangeRateManager:217: Starting exchange rate manager
2018-08-14 17:42:56,839 INFO     lbrynet.core.RateLimiter:72: Starting rate limiter.
2018-08-14 17:42:56,937 INFO     lbrynet.daemon.Components:259: victor.lbry.tech:50001 height: 419990, local height: 419990
2018-08-14 17:42:58,943 WARNING  lbrynet.daemon.Components:692: failed to set up redirect with txupnp, miniupnpc fallback was successful
2018-08-14 17:42:59,015 INFO     lbrynet.dht.protocol:202: DHT listening on UDP 4446 (ext port 4446)
2018-08-14 17:42:59,015 INFO     lbrynet.daemon.Components:417: Started the dht
2018-08-14 17:42:59,016 INFO     lbrynet.core.Wallet:92: Starting wallet.
2018-08-14 17:42:59,053 INFO     lbrynet.core.Wallet:880: Loading the wallet
2018-08-14 17:43:01,259 WARNING  lbrynet.core.Wallet:963: Your wallet is excessively large (2687 addresses), please follow instructions here: https://github.com/lbryio/lbry/issues/437 to reduce your wallet size
2018-08-14 17:43:01,292 INFO     lbrynet.dht.node:250: Attempting to join the DHT network, 0 contacts known so far
2018-08-14 17:43:03,947 INFO     lbrynet.core.Wallet:978: Local Height: 419990, remote height: 419990, behind: 0
2018-08-14 17:43:03,948 INFO     lbrynet.core.Wallet:986: Wallet Loaded
2018-08-14 17:43:03,950 INFO     lbrynet.core.Wallet:903: Subscribing to addresses
2018-08-14 17:43:04,151 INFO     lbrynet.core.Wallet:905: Synchronized wallet
2018-08-14 17:43:04,161 INFO     lbrynet.core.Wallet:907: Set up lbryum command runner
2018-08-14 17:43:04,490 INFO     lbrynet.daemon.Components:602: Peer protocol listening on TCP 3335 (ext port 3335)
2018-08-14 17:43:04,490 INFO     lbrynet.daemon.Components:555: Starting the file manager
2018-08-14 17:43:04,505 INFO     lbrynet.daemon.auth.server:231: shutting down before finished starting
2018-08-14 17:43:04,506 INFO     lbrynet.dht.protocol:493: Stopping DHT
2018-08-14 17:43:04,507 INFO     lbrynet.dht.protocol:496: DHT stopped
2018-08-14 17:43:04,572 INFO     lbrynet.daemon.Components:615: Stop listening on port 3335
2018-08-14 17:43:04,573 INFO     lbrynet.core.Wallet:104: Stopping wallet.
2018-08-14 17:43:04,668 INFO     lbrynet.core.Wallet:932: Stopped wallet
2018-08-14 17:43:04,670 INFO     lbrynet.core.Wallet:935: Stopped connection to lbryum server
```

**Closed by tzarebczan** 2018-08-14 21:45 UTC
Labels: area: other, good first issue, help wanted, level: 1, type: bug
