### ISSUE TITLE
`claim_new_support` should not require a name arg

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry#871] opened 2017-08-25 14:17 UTC
It already requires claim_id, so it can look up the claim from that

**Comment by MSFTserver** [comment] 2017-08-28 12:35
upon entering a different name for this command it generates a new url and replaces the old one within the publishes section of the app and doesn't know what to so with itself, the name I think should be allocated from the id I would presume?
[.GIF of Issue](https://files.slack.com/files-pri/T0AFFTU95-F6UFHL6Q3/5.gif)

**Comment by tzarebczan** [comment] 2017-08-28 13:27
Yea that's a nasty one. I think part of it is fixed by @hackrush01 in master already.

This is also related: https://github.com/lbryio/lbry/issues/812

**Comment by alyssaoc** [comment] 2018-08-02 13:51
closing as a duplicate of #812

**Closed by alyssaoc** 2018-08-02 13:51 UTC
Labels: area: jsonrpc, help wanted, level: 1, type: bug
