### ISSUE TITLE
pooled Claims

### ISSUE THREAD

**Issue by DrAlta** [lbryio/lbry#1322] opened 2018-07-27 15:32 UTC
It should be easy to pool your LBC on a community claim with the same ease of withdrawal of deposit as  a single person claim.
'
I think the easiest way to implement this is to sum all that claims that share the same name and destination. Not only should this be easy to code. it would be intuitive and wouldn't require much coordination a upon contributors to a pooled claim. Anybody could contribute to a pool at any time be placing a new claim on that name with the same address for the destination and could withdraw support form the pool by 
 

## The Issue
It would be good if people could join together and pool their LBC in claim with the same ease and features as a single publisher claim

### Expected behaviour
So for example Alice has a 30 LBC claim of 'Foo' to point at 'Chip', Bob and Carol each have 20 LBC they want to deposit for 'Foo' to point to  'Dale'.  Currently if they each place a 20 claim for the name 'Foo' Alice's 'Chip' would be the result for a look up of the name 'Foo'.

### Actual behaviour
rouse@discord told me to submit this as a issue so I'm assuming that currently it doesn't work this way.  
Thou it is implied on the FAQ that it is supposed to work this way(if a 'publish' is take to mean a name/target pair).
I think it just checks which claim has the highest LBC assigned to it. 
I believe you can support a claim by depositing LBC for it but allowing multiple valid claims that point the same name to the same target that don't contribute to each other is bad User Interface design.

I think that supported claims should be when you trust the publisher to update the target.

So you support a publisher on a name and that publisher can freely change the target and the pledged amount automatically goes to the new name-claim.

**Comment by tzarebczan** [comment] 2018-07-27 23:01
@DrAlta thanks for opening this and the discussion on Discord. Based on what you were looking for, I don't think this fits in with how the LBRY protocol/bidding system was designed to work. Claim supports are possible using the https://lbryio.github.io/lbry/cli/#Claim_new_support call, but they are specific to a claim ID, and not just a name.

Names are intended not to be unique, giving users the option to bid on vanity URLs with the option of using a claim modifier for uniqueness. See https://lbry.io/faq/naming

Per our discussion, the use case you were looking for is closing to a claim playlist/aliasing feature. Something similar was filed on the app https://github.com/lbryio/lbry-desktop/issues/619 and I'll follow up with the required issue on this repository.

**Closed by tzarebczan** 2018-07-27 23:01 UTC
Labels: needs: triage
