### ISSUE TITLE
Updating channel claim zeroes the effective_amount

### ISSUE THREAD

**Issue by billbitt** [lbryio/lbry#943] opened 2017-10-10 14:10 UTC
## The Issue
I tried to update my channel's claim amount.  I made a claim of 10, and it resulted in the effective_amount going to 0.

### Steps to reproduce
1. use curl to create a channel claim
2. use curl to create another claim to that channel.
see below:
``` 
$ curl 'http://localhost:5279/lbryapi' --data '{"method":
"channel_new","params":{"channel_name": "@lbry", "amount": 10}}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "amount": "10",
    "claim_id": "3fda836a92faaceedfe398225fb9b2ee2ed1f01a",
    "fee": "0.000253",
    "nout": 0,
    "success": true,
    "tx": "0100000002c00b9bbd1c3d2625d9ab62bdb2d9283d0543ae4f7c3059ccc211bd318e8
5077c000000006b483045022100ac765c755c21e52ed691030a3cc8569ac0872e13a4a7d1e3a68c8
9aca7bbf0bc0220166fb05778117309118fe6794442144d5c15c277fd4dee81ab352b7659c03b230
12102ec2f46fdac3b26e0460034e2257d9105235504722405b7b5c7a5e7e5f3245285ffffffff125
3dd68f1aacc1cde7dfba8b6f10b0e64ea4bbf472524142897b5ae2079c26f010000006b483045022
100ec34f669ee936f0bbae0e50864ae698989fc37045bae08a1ae412e3e92d54f980220038591864
d442785b16e1a6a11e1b7d469d5aba7a5f9a0e5fbb660758fb78563012102dcd95ea03e8f661d41b
5df54fd8a85b87ffac87a9db4f67749baab4c5f912cbbffffffff0200ca9a3b000000009db705406
c627279141af0d12eeeb2b95f2298e3dfeeacfa926a83da3f4c6408011002225e080110032258305
6301006072a8648ce3d020106052b8104000a03420004bbfe30d859ddbdad2c35dcae6dfed9761bb
7b89704ec27ab11db9668399104e4684f88e525e900b5749b5cf081a5c9805d2d8302c53b13554a0
21563c6e1e4566d6d76a91451cfc0f83848e8579ef25078c79ecd2d1ac44c8f88ac96d6060000000
0001976a91436ebded58c68799f8d24dc9fb80663cc68c20ea488ac00000000",
    "txid": "09f70e88e8b13ffd7e55537dc73f8491cf73f06e17383f3ffcbe0779d80d23fd"
  }
}

$ curl 'http://localhost:5279/lbryapi' --data '{"method":
"resolve","params":{"uri": "@lbry#3fda836a92faaceedfe398225fb9b2ee2ed1f01a"}}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "@lbry#3fda836a92faaceedfe398225fb9b2ee2ed1f01a": {
      "certificate": {
        "address": "bLBrJkkrWedQ1yhHAChS7wBNtwif4YtGzp",
        "amount": 0.1,
        "claim_id": "3fda836a92faaceedfe398225fb9b2ee2ed1f01a",
        "claim_sequence": 10,
        "decoded_claim": true,
        "depth": 6,
        "effective_amount": 0.0,
        "has_signature": false,
        "height": 253176,
        "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a
03420004bbfe30d859ddbdad2c35dcae6dfed9761bb7b89704ec27ab11db9668399104e4684f88e5
25e900b5749b5cf081a5c9805d2d8302c53b13554a021563c6e1e456",
        "name": "@lbry",
        "nout": 0,
        "supports": [],
        "txid": "09f70e88e8b13ffd7e55537dc73f8491cf73f06e17383f3ffcbe0779d80d23f
d",
        "valid_at_height": 256320,
        "value": {
          "certificate": {
            "keyType": "SECP256k1",
            "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004bbfe30
d859ddbdad2c35dcae6dfed9761bb7b89704ec27ab11db9668399104e4684f88e525e900b5749b5c
f081a5c9805d2d8302c53b13554a021563c6e1e456",
            "version": "_0_0_1"
          },
          "claimType": "certificateType",
          "version": "_0_0_1"
        }
      },
      "claims_in_channel": 4
    }
  }
}
```

### Expected behaviour
The effective amount should be updated.

### Actual behaviour
the effective amount became 0.0

## System Configuration
``` lbry@ip-172-55-1-123:~$ curl 'http://localhost:5279/lbryapi' --data '{"method":
"version"}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "****",
    "lbrynet_version": "0.16.4",
    "lbryschema_version": "0.0.12rc1",
    "lbryum_version": "3.1.9rc2",
    "os_release": "4.4.0-93-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
} 
```

**Comment by tzarebczan** [comment] 2017-10-10 14:24
I think the effective amount takes 6 confirmations to show correctly - can you check it again in a couple? Same thing happens on claims or when adding supports.

**Comment by billbitt** [comment] 2017-10-10 14:28
I made the update yesterday and it still had not updated this morning.  by contrast, the update I made to @lbrycom worked fine and the effective_amount was increased after only a couple confirmations:
```
lbry@ip-172-55-1-123:~$ curl 'http://localhost:5279/lbryapi' --data '{"method":

"resolve","params":{"uri": "@lbrycom#2280704e73a80444d0dac07d54d90c503d02d588"}
}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "@lbrycom#2280704e73a80444d0dac07d54d90c503d02d588": {
      "certificate": {
        "address": "bZZmUFr5QKMLgK33xC5uVsyQUQT5BVrZ5i",
        "amount": 0.1,
        "claim_id": "2280704e73a80444d0dac07d54d90c503d02d588",
        "claim_sequence": 1,
        "decoded_claim": true,
        "depth": 487,
        "effective_amount": 10.0,
        "has_signature": false,
        "height": 253168,
        "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a
034200043213b26c64dde9b8c483f4e91237700390b0e128103778acac38a2e81cb2aa16e944c4ae
f5aaeca7fb3f332e013615108cba79afa05603592bed1a72df0b38ad",
        "name": "@lbrycom",
        "nout": 0,
        "supports": [],
        "txid": "048866a8b1e99b2192d1b58ef071c3b7338a50c3dd70ffe9c01e9493632a293
3",
        "valid_at_height": 253168,
        "value": {
          "certificate": {
            "keyType": "SECP256k1",
            "publicKey": "3056301006072a8648ce3d020106052b8104000a034200043213b2
6c64dde9b8c483f4e91237700390b0e128103778acac38a2e81cb2aa16e944c4aef5aaeca7fb3f33
2e013615108cba79afa05603592bed1a72df0b38ad",
            "version": "_0_0_1"
          },
          "claimType": "certificateType",
          "version": "_0_0_1"
        }
      },
      "claims_in_channel": 1
    }
  }
}
```

**Comment by tzarebczan** [comment] 2017-10-10 14:34
You are right. Let's see if https://lbryio.github.io/lbry/cli/#claim_new_support works now and I'll try to reproduce the issue. I can see the tx has the 10 LBC, so something is definitely wonky.

**Comment by billbitt** [comment] 2017-10-10 14:39
cool.  here is my claim_new_spport tx...
```$ curl 'http://localhost:5279/lbryapi' --data '{"method":
"claim_new_support", "params": {
>   "name": "@lbry",
>   "claim_id": "3fda836a92faaceedfe398225fb9b2ee2ed1f01a",
>   "amount": 5
> }}'
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "fee": 0.000128,
    "nout": 0,
    "tx": "0100000001f9a88a255ae232061d6659ae63c1a952c6bf4d0b0d16fc4af925e90c348
06825010000006b483045022100e5795b7466254cfd1439c13bd66e3f0fb36c8b40d234a147a4407
0672c55fe6802204f146b0d62847a6db6ba0233d83bf7632a22193344f1ed1f7dc26d11d4aab31b0
121034bd5bf88cb0396a45d1f7e4c5db76a0b1e56a822b3259671843b7287a0d4e857ffffffff020
065cd1d0000000037b605406c627279141af0d12eeeb2b95f2298e3dfeeacfa926a83da3f6d7576a
914955fba7c4e0e5078fc95fdf15102764964d6c68888ac30c8d081000000001976a914f58074e8a
7f19f329138ee799447fa48d1dda66588ac00000000",
    "txid": "bd9f27263fbcab35239a56b298d4192c15052f9be0c18d275015e4e78ed41b68"
  }
}```

**Comment by tzarebczan** [comment] 2017-10-10 15:25
Resolve still showing 0 after adding your support. Claim_list shows 5.1 effective amount haha (taking original claim amount + supports).
```
{
  "address": "bLBrJkkrWedQ1yhHAChS7wBNtwif4YtGzp",
  "amount": 0.1,
  "claim_id": "3fda836a92faaceedfe398225fb9b2ee2ed1f01a",
  "claim_sequence": 10,
  "decoded_claim": true,
  "effective_amount": 5.1,
  "has_signature": false,
  "height": 253176,
  "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004bbfe30d859ddbdad2c35dcae6dfed9761bb7b89704ec27ab11db9668399104e4684f88e525e900b5749b5cf081a5c9805d2d8302c53b13554a021563c6e1e456",
  "name": "@lbry",
  "nout": 0,
  "supports": [
    {
      "amount": 5.0,
      "nout": 0,
      "txid": "bd9f27263fbcab35239a56b298d4192c15052f9be0c18d275015e4e78ed41b68"
    }
  ],
  "txid": "09f70e88e8b13ffd7e55537dc73f8491cf73f06e17383f3ffcbe0779d80d23fd",
  "value": {
    "certificate": {
      "keyType": "SECP256k1",
      "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004bbfe30d859ddbdad2c35dcae6dfed9761bb7b89704ec27ab11db9668399104e4684f88e525e900b5749b5cf081a5c9805d2d8302c53b13554a021563c6e1e456",
      "version": "_0_0_1"
    },
    "claimType": "certificateType",
    "version": "_0_0_1"
  }
}
```

**Comment by tzarebczan** [comment] 2017-10-10 15:54
Another issue with effective amount when resolving a claim under that channel - looks like its showing the original claim amount and not the effective amount. 
{
  "lbry://Iwilltauntyouasecondtime#e859fb441c9fc0d77d8d641b91e369cc0789e980": {
    "certificate": {
      "address": "bTUr1eijJFNqYT4WsJMsdXLrYTTPLHvzXi",
      "amount": 0.1,
      "claim_id": "3fda836a92faaceedfe398225fb9b2ee2ed1f01a",
      "claim_sequence": 10,
      "decoded_claim": true,
      "depth": 3,
      "effective_amount": 0.0,
      "has_signature": false,
      "height": 253685,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004bf069ae512dcfc6aca2c04b983dbc983be0e3111e3d15366851a5938f509a13936d15822e89839397acf0634eecf755bf0525c2516c68b91c5ca15b887296bbf",
      "name": "@lbry",
      "nout": 0,
      "supports": [
        {
          "amount": 5.0,
          "nout": 0,
          "txid": "bd9f27263fbcab35239a56b298d4192c15052f9be0c18d275015e4e78ed41b68"
        },
        {
          "amount": 2.0,
          "nout": 0,
          "txid": "082b4276da8eb12561c9b5abc6ab55990684b5e94d4b12276042e0bbce7aa194"
        },
        {
          "amount": 3.0,
          "nout": 0,
          "txid": "e5322528d10cab8af9f04fc7c080f6203d020ea94175db65dffe6ce45fcc9f57"
        }
      ],
      "txid": "66c893e5daa901c32fc4adc115fbc62c430e39836ae8b8985d3c6f3a6dafe24c",
      "valid_at_height": 256845,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004bf069ae512dcfc6aca2c04b983dbc983be0e3111e3d15366851a5938f509a13936d15822e89839397acf0634eecf755bf0525c2516c68b91c5ca15b887296bbf",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    "claim": {
      "address": "banpwixPosfVDWnGvXqU2af36Qpsd7buGd",
      "amount": 0.01,
      "channel_name": null,
      "claim_id": "e859fb441c9fc0d77d8d641b91e369cc0789e980",
      "claim_sequence": 1,
      "decoded_claim": true,
      "depth": 344,
      "effective_amount": 0.01,
      "has_signature": true,
      "height": 253344,
      "hex": "080110011ab5010801126e080410011a184977696c6c7461756e74796f75617365636f6e6474696d65222e4977696c6c7461756e74796f75617365636f6e6474696d65207075626c69736865642076696120737065652e63682a07737065652e6368320d5075626c696320446f6d61696e38004a0052005a001a41080110011a30ddd6d9d0a92158f3945903b12dce687987d27ac75c3519d1efa70c602d69a55235284ac08b94e2f00329f289c90cfdc42209696d6167652f6769662a5c080110031a40f0f07f05ad37e4dcf77043c9885ec1bc4b5b31b1a3f3cefacea7e1c4a4757604d5ad25cb4bc06768ae4992174244e3a10f4061cddeedf0d2bbfc13fd36f235eb22143fda836a92faaceedfe398225fb9b2ee2ed1f01a",
      "name": "Iwilltauntyouasecondtime",
      "nout": 0,
      "signature_is_valid": false,
      "supports": [],
      "txid": "256880340ce925f94afc160d0b4dbfc652a9c163ae59661d0632e25a258aa8f9",
      "valid_at_height": 253344,
      "value": {
        "claimType": "streamType",
        "publisherSignature": {
          "certificateId": "3fda836a92faaceedfe398225fb9b2ee2ed1f01a",
          "signature": "f0f07f05ad37e4dcf77043c9885ec1bc4b5b31b1a3f3cefacea7e1c4a4757604d5ad25cb4bc06768ae4992174244e3a10f4061cddeedf0d2bbfc13fd36f235eb",
          "signatureType": "SECP256k1",
          "version": "_0_0_1"
        },
        "stream": {
          "metadata": {
            "author": "spee.ch",
            "description": "Iwilltauntyouasecondtime published via spee.ch",
            "language": "en",
            "license": "Public Domain",
            "licenseUrl": "",
            "nsfw": false,
            "preview": "",
            "thumbnail": "",
            "title": "Iwilltauntyouasecondtime",
            "version": "_0_1_0"
          },
          "source": {
            "contentType": "image/gif",
            "source": "ddd6d9d0a92158f3945903b12dce687987d27ac75c3519d1efa70c602d69a55235284ac08b94e2f00329f289c90cfdc4",
            "sourceType": "lbry_sd_hash",
            "version": "_0_0_1"
          },
          "version": "_0_0_1"
        },
        "version": "_0_0_1"
      }
    },
    "claims_in_channel": 0
  }
}

**Comment by tzarebczan** [comment] 2017-10-10 17:00
So the problem is that the original claim owner on @lbry has held it for a while, so there is a waiting period for you to overtake it.  Current content bot shows: lbry://@lbry
Takes effect on approx. *October 16th at 13:04 UTC* (block 256845)
Block 253685 • Claim ID 3fda836a92faaceedfe398225fb9b2ee2ed1f01a

I think we should show the effective amount immediately to avoid confusion and help with claim/channel bidding in some other tickets we have filed. This would require some other status or processing to tell if the claim is at the appropriate block height.  

Let me check with Jack/Kay on this and then I'l open a new issue. 

These are all the claims for @lbry -
```
C:\Program Files (x86)\LBRY\resources\app\dist>lbrynet-cli claim_list --name=@lbry
{
  "claims": [
    {
      "address": "bDWhrFs43JyHAXcnvM27EE4pwRcYc2zCUN",
      "amount": 1e-05,
      "claim_id": "5b08b23ee0fd05e908274be91987d7e6a48ef201",
      "claim_sequence": 2,
      "decoded_claim": true,
      "depth": 61291,
      "effective_amount": 1e-05,
      "has_signature": false,
      "height": 192422,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a034200041c20394f24ada05bac64cf93df7d1028001b707f1ebfc7a47e5c9a8ac87444a63bcc8715f4b728404ae9ecc2ff86121396b7ede064834144504877432ad43ffe",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "28a9b499f8709d838b1b9f331f964cbbc6c33a54a25d8cd1fe43375f94e9bbbe",
      "valid_at_height": 193667,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a034200041c20394f24ada05bac64cf93df7d1028001b707f1ebfc7a47e5c9a8ac87444a63bcc8715f4b728404ae9ecc2ff86121396b7ede064834144504877432ad43ffe",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bYbpapJCTxg7JCeJxU2Qc67eL6wiSAJdi8",
      "amount": 1.0,
      "claim_id": "459235d496ba3a43c7e90c7f686f9c3b1559de0f",
      "claim_sequence": 7,
      "decoded_claim": true,
      "depth": 37528,
      "effective_amount": 1.0,
      "has_signature": false,
      "height": 216185,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004ffecab5279c8ed1914d11015270298c1a52a260e69fad12a0edbebb5f5860d4ff557e77c5966f3156a9904da4e90c6778b338b81666e2e8697385a379056f7f5",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "f66d867cf6b3573cbd1520e7f21c7e42c00ad54289ba224de89f6fe3f0d4f6df",
      "valid_at_height": 218173,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004ffecab5279c8ed1914d11015270298c1a52a260e69fad12a0edbebb5f5860d4ff557e77c5966f3156a9904da4e90c6778b338b81666e2e8697385a379056f7f5",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bXGh6GtrwyNzdrobKiVc5NtyYy9CfH9dcF",
      "amount": 1.0,
      "claim_id": "2ef21d492d5ac2cef8afa447800957cce832c715",
      "claim_sequence": 8,
      "decoded_claim": true,
      "depth": 28932,
      "effective_amount": 1.0,
      "has_signature": false,
      "height": 224781,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a034200042e141b59f080bb277f613d874cc5ea7dea6808f73161a9fc60936b6103dee8ece9bf31799110024110fcf76a1abf600a012e2c4d61a20f2b04a2039864c27770",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "c720784aac78cb3591c248099da32e8440c59eb37c82f7d32890ece96531688f",
      "valid_at_height": 227038,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a034200042e141b59f080bb277f613d874cc5ea7dea6808f73161a9fc60936b6103dee8ece9bf31799110024110fcf76a1abf600a012e2c4d61a20f2b04a2039864c27770",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bTUr1eijJFNqYT4WsJMsdXLrYTTPLHvzXi",
      "amount": 0.1,
      "claim_id": "3fda836a92faaceedfe398225fb9b2ee2ed1f01a",
      "claim_sequence": 10,
      "decoded_claim": true,
      "depth": 28,
      "effective_amount": 0.0,
      "has_signature": false,
      "height": 253685,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004bf069ae512dcfc6aca2c04b983dbc983be0e3111e3d15366851a5938f509a13936d15822e89839397acf0634eecf755bf0525c2516c68b91c5ca15b887296bbf",
      "name": "@lbry",
      "nout": 0,
      "supports": [
        {
          "amount": 5.0,
          "nout": 0,
          "txid": "bd9f27263fbcab35239a56b298d4192c15052f9be0c18d275015e4e78ed41b68"
        },
        {
          "amount": 2.0,
          "nout": 0,
          "txid": "082b4276da8eb12561c9b5abc6ab55990684b5e94d4b12276042e0bbce7aa194"
        },
        {
          "amount": 3.0,
          "nout": 0,
          "txid": "e5322528d10cab8af9f04fc7c080f6203d020ea94175db65dffe6ce45fcc9f57"
        }
      ],
      "txid": "66c893e5daa901c32fc4adc115fbc62c430e39836ae8b8985d3c6f3a6dafe24c",
      "valid_at_height": 256845,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004bf069ae512dcfc6aca2c04b983dbc983be0e3111e3d15366851a5938f509a13936d15822e89839397acf0634eecf755bf0525c2516c68b91c5ca15b887296bbf",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bMAoFddXDSMb8ArqMg85jxk9HtrMrUKczf",
      "amount": 0.1,
      "claim_id": "0ce538359c0ea82ee6277e1cbff203a9fe17e053",
      "claim_sequence": 4,
      "decoded_claim": true,
      "depth": 51990,
      "effective_amount": 0.1,
      "has_signature": false,
      "height": 201723,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004461f7986b3aa7afa0ef37c81448ea8a7bf4945bdca5502e34be1fa3178ae7d181ffb28eb56071e2e9ba1611a2e285319d69c38f1dde74eace8db5000907fb7a5",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "00e13841f51e6e0b52d0fb803bee3df7bc05a1c3dccc701040b448472da1e2c4",
      "valid_at_height": 203259,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004461f7986b3aa7afa0ef37c81448ea8a7bf4945bdca5502e34be1fa3178ae7d181ffb28eb56071e2e9ba1611a2e285319d69c38f1dde74eace8db5000907fb7a5",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bT3sNDN31d46NjQMpTKBbvhVHkehY775HM",
      "amount": 0.01,
      "claim_id": "6c157cae05894cb5b88dce9587e97557e760716f",
      "claim_sequence": 6,
      "decoded_claim": true,
      "depth": 41548,
      "effective_amount": 0.01,
      "has_signature": false,
      "height": 212165,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004ed932d7d7d0d55792212b3b787988c487be567757e21c1791d7b38ece0bf4cb53b274de835787cd24d9702ae362b3745a6cbd7756d2e45c9b0229198ae3267bd",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "62aedc4d98da4197ff6a55cea8e6d8fbfffcdf24498c73f1b67dd6ba903ac618",
      "valid_at_height": 214027,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004ed932d7d7d0d55792212b3b787988c487be567757e21c1791d7b38ece0bf4cb53b274de835787cd24d9702ae362b3745a6cbd7756d2e45c9b0229198ae3267bd",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bT2Mzrx4aFJXVuJ58TWPWRuGmrwvb3XZPg",
      "amount": 0.1,
      "claim_id": "628b0635ff8ecc22573b2f3e2ffd4d8f25e8c396",
      "claim_sequence": 9,
      "decoded_claim": true,
      "depth": 17473,
      "effective_amount": 0.1,
      "has_signature": false,
      "height": 236240,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004633a4f5d5d5c667f79aa797f1d0ee293e02df0dc18d8f1e149bd20fc92f2d8f8ca7e0fc63c4e43125c176b8d5149fc49ed1d93a6b4523b6f6ff022fefd7aee38",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "d98a8e521ca1024d5778349647b3d288f46bcc482ac5f89b25cc68e524773ead",
      "valid_at_height": 238855,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004633a4f5d5d5c667f79aa797f1d0ee293e02df0dc18d8f1e149bd20fc92f2d8f8ca7e0fc63c4e43125c176b8d5149fc49ed1d93a6b4523b6f6ff022fefd7aee38",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bUFjGBN7JSR3iMHZm1MGvMQEY9uVTZNHiN",
      "amount": 0.01,
      "claim_id": "1c119c6772690874c9ddb2fb59d8a86ebd7c26ae",
      "claim_sequence": 3,
      "decoded_claim": true,
      "depth": 53480,
      "effective_amount": 0.01,
      "has_signature": false,
      "height": 200233,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a034200048be7c0fef3ae98337b3439741f2f373b739bc291c9af1bbc6e173af232af5fe640ce56fce731a829d3cdedcef5509aa379399e3228277d1da7a11b962779450a",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "5dc43e2341b0888f69ebf37ceaf2a25b339f9aa73a2e738a1cfe906e274be909",
      "valid_at_height": 201723,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a034200048be7c0fef3ae98337b3439741f2f373b739bc291c9af1bbc6e173af232af5fe640ce56fce731a829d3cdedcef5509aa379399e3228277d1da7a11b962779450a",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bNCEx3PT57cCnLiiEWy2rULehQSL5BdfCZ",
      "amount": 0.01,
      "claim_id": "c97b6b3f1cff7fa3d758bbe72c4faa0532e571ef",
      "claim_sequence": 5,
      "decoded_claim": true,
      "depth": 50616,
      "effective_amount": 0.01,
      "has_signature": false,
      "height": 203097,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004788bca1f0f28a9571fae2b9a268938f50ec3aca182fa4d12ad543bb8e5bd32fa3c3afc06c6ce3cabecd6c48803c3c729ddc17fefe72e00bf94dfce7accaa1d42",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "ee223183500e4ca48c493fefbc9c88f2f0ba02b6f7c41086eb19d701e6e34e42",
      "valid_at_height": 204676,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004788bca1f0f28a9571fae2b9a268938f50ec3aca182fa4d12ad543bb8e5bd32fa3c3afc06c6ce3cabecd6c48803c3c729ddc17fefe72e00bf94dfce7accaa1d42",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    },
    {
      "address": "bEVQ1hDL7xS7ZTmQKsN22Cjs5oPg5nhA2w",
      "amount": 1.0,
      "claim_id": "bef634cc6edc05ebd2648b7705e1edc5531d4df1",
      "claim_sequence": 1,
      "decoded_claim": true,
      "depth": 101161,
      "effective_amount": 1.0,
      "has_signature": false,
      "height": 152552,
      "hex": "08011002225e0801100322583056301006072a8648ce3d020106052b8104000a03420004c70d122054ef0086504df833c59463216296bf245ea9763c0aa85a77963e96180b56b976b6382de2a507abc824f255c7198a316efba5819b758cd7a888d442e9",
      "name": "@lbry",
      "nout": 0,
      "supports": [],
      "txid": "8f370928ec53fca70e90d518a74ab095a7c3c634dba18e64291b996811e1be3b",
      "valid_at_height": 152552,
      "value": {
        "certificate": {
          "keyType": "SECP256k1",
          "publicKey": "3056301006072a8648ce3d020106052b8104000a03420004c70d122054ef0086504df833c59463216296bf245ea9763c0aa85a77963e96180b56b976b6382de2a507abc824f255c7198a316efba5819b758cd7a888d442e9",
          "version": "_0_0_1"
        },
        "claimType": "certificateType",
        "version": "_0_0_1"
      }
    }
  ],
  "last_takeover_height": 152552,
  "supports_without_claims": []
}
```

**Comment by tzarebczan** [comment] 2017-10-10 21:42
Bill - thanks for exposing this. I knew that it happened, but didn't realize it was a bug that it showed 0.  Opened https://github.com/lbryio/lbryum/issues/158 to fix the underlying issue

**Closed by tzarebczan** 2017-10-10 21:42 UTC
Labels: bug
