### ISSUE TITLE
Unpredictable Changes in Wallet Credits

### ISSUE THREAD

**Issue by ShakharDasgupta** [lbryio/lbry#538] opened 2017-03-17 14:23 UTC
## The Issue
Wallet Credits are changing in unpredictable ways.
### Steps to reproduce
1. Receive credits from [https://lbry.io/quickstart/credits](url)
2. Check credits using `curl 'http://localhost:5279/lbryapi' --data '{"method":"wallet_balance"}'`
3. Publish something.
4. Check credits again.
5. Download "It's a Disaster".
6. Check credits again.

### Actual behaviour
1. Had 50 credits in the wallet after receiving credits by using my Github account.
2. After making several attempts to publish a video (failed because of bad metadata), checked credits and found that I had 48.** credits.
3. Successfully published a video and got 200 more credits which added up to 248.** credits.
4. Tried to download "It's a Disaster" but the download failed due to insufficient credits and I had -111.** (negative) credits.
5. Tried to download "It's a Disaster" again. The download started and I had 68.70 credits. But the download did not complete due to Issue #533.

## System Configuration

 

{
    "lbrynet_update_available": false,
    "lbrynet_version": "0.9.0",
    "lbryum_version": "2.7.13",
    "os_release": "4.9.7-201.fc25.x86_64",
    "os_system": "Linux",
    "platform": "Linux-4.9.7-201.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five",
    "remote_lbrynet": "0.9.0",
    "ui_version": "not loaded yet"
  }

## Anything Else
Please mention about the required fields for metadata under the Publishing section in [https://lbry.io/quickstart/credits](url).

**Comment by jackrobison** [comment] 2017-03-21 21:57
4 - This sounds like improper queueing of payments/not handling unconfirmed claims and balances properly, will look into it

5 - This is a dht bug that happens only on linux, will look into it

**Comment by snodnipper** [comment] 2017-05-29 12:20
I had the same issue running the [docker container](https://hub.docker.com/r/flungo/lbry.io/).

Furthermore, I had an access token issue when trying to send credits.

![lbry](https://cloud.githubusercontent.com/assets/576719/26549546/79e620a4-4471-11e7-9efc-42ef04e0117c.png)

**Comment by kauffj** [comment] 2017-07-17 19:31
Fixed soon (or already?) and duplicate of #747

**Closed by kauffj** 2017-07-17 19:31 UTC
Labels: bug, P2
