### ISSUE TITLE
Federated wallet server network

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry#2108] opened 2019-05-10 16:31 UTC
## The Issue
In the future, we'll want anyone to be able to run a wallet server and have the SDK "know" about it. Currently we are using fixed servers from our config.

https://electrumx.readthedocs.io/en/latest/peer_discovery.html

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lyoshenka** [comment] 2019-05-20 19:29
actually this is a dupe of #2114

**Closed by lyoshenka** 2019-05-20 19:29 UTC
Labels: area: wallet server
